# This is a basic workflow to help you get started with Actions

name: Create FRBDK deliverables

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ $default-branch, NetStandard ]
  pull_request:
    branches: [ $default-branch, NetStandard ]

  # Allows you to run this workflow manually from the Actions tab
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  
    strategy:
      matrix:
        configuration: [Debug] #, Release]
        platform: [x86]

    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check out this repository ($GITHUB_WORKSPACE)
      # Checking out to deeper location to appease the relative path reference to Gum (..\..\..\Gum).
      - uses: actions/checkout@v2
        with:
          # repository: $GITHUB_WORKSPACE
          path: 'extra-depth-for-gum-reference\FlatRedBall'

      # Check out dependency repos to desired location for GitHub Actions
      # Else: "D:\a\FlatRedBall\FlatRedBall\FRBDK\Glue\Glue with All.sln.metaproj : error MSB3202: The project file "D:\a\FlatRedBall\Gum\GumRuntime\GumRuntime.csproj" was not found. [D:\a\FlatRedBall\FlatRedBall\FRBDK\Glue\Glue with All.sln]"
      - uses: actions/checkout@v2
        with:
          repository: 'patridge/Gum'
          path: 'extra-depth-for-gum-reference\Gum'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore Gum NuGet Packages
        run: nuget restore "extra-depth-for-gum-reference\Gum\Gum.sln"

      # Trying to work through error:
      # > D:\a\FlatRedBall\FlatRedBall\Gum\GumRuntime\GumRuntime.csproj(132,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\FlatRedBall\FRBDK\Glue\packages\MonoGame.Framework.DesktopGL.Core.3.8.0.13\build\MonoGame.Framework.DesktopGL.Core.targets.
      # D:\a\FlatRedBall\FlatRedBall\Gum\GumRuntime\[GumRuntime.csproj]
      # + ..\..\FlatRedBall\FRBDK\Glue\packages\
      # => D:\a\FlatRedBall\FlatRedBall\FlatRedBall\FRBDK\Glue\packages\
      # But that makes no sense to me.
      # Next error after adding another \FlatRedBall
      # > D:\a\FlatRedBall\FlatRedBall\extra-depth-for-gum-reference\FlatRedBall\FRBDK\Glue\Glue with All.sln.metaproj : error MSB3202: The project file "D:\a\FlatRedBall\FlatRedBall\extra-depth-for-gum-reference\Gum\GumRuntime\GumRuntime.csproj" was not found. [D:\a\FlatRedBall\FlatRedBall\extra-depth-for-gum-reference\FlatRedBall\FRBDK\Glue\Glue with All.sln]
      - name: Restore GumRuntime NuGet Packages # Should these be restored via some containing solution?
        run: nuget restore "extra-depth-for-gum-reference\Gum\GumRuntime\packages.config" -PackagesDirectory "extra-depth-for-gum-reference\FlatRedBall\FRBDK\Glue\packages"

      - name: Restore NuGet Packages
        run: nuget restore "extra-depth-for-gum-reference\FlatRedBall\FRBDK\Glue\Glue with All.sln" # TODO: Try forward slash

      - name: Build solution
        run: msbuild "extra-depth-for-gum-reference\FlatRedBall\FRBDK\Glue\Glue with All.sln" /p:Configuration="${{ matrix.configuration }}" /p:Platform="${{ matrix.platform}}"
        # /p:Configuration=$env:Configuration # Failed as empty
        #  /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: published_webapp
          path: bin\Release\Publish